### ISSUE TITLE
story: add reporters in JUNIT and GH Actions summary format

### ISSUE THREAD

**Issue by tnolet** [checkly/checkly-cli#554]
### Story description

Having structured test output inside CI and test management tooling is useful for quickly seeing what checks failed on `test` without having to view the logs. We want to support this by introducing `reporters` so a user can configure a reporter type. This pattern should be very familiar from Jest and [Playwright reporters](https://playwright.dev/docs/test-reporters)

# GH Actions Job Summary

- Failed / Passed state
- Duration
- Check Type
- Link to Test Overview
- Link to Test Session

Failing checks should be sorted to the top

See
- [Job summaries landing](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/)
- [Job Summary docs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary)

# Junit

TBD:  We need to research how Junit format can map to `checkly test` output.

# `reporter` flag

Introduce a new flag `--reporter / -r` that takes the name of a supported reporter.
For reporters that are best consumed as files, like Junit, a user should be able to set an output file via an env variable, i.e. `CHECKLY_REPORTER_JUNIT_OUTPUT`

# `reporter` Project property

The `reporter` property should also be under the `cli` section in the Project config. A user should be able to list multiple reporters and add the `outputFile` for reporter where it makes sense, like Junit.

### Tasks
- [x] Add `--reporter` flag to the `test` command https://github.com/checkly/checkly-cli/pull/598
- [x] Add Github reporter https://github.com/checkly/checkly-cli/pull/601
- [ ] Add JUnit reporter
- [ ] Add `cli.reporters` configuration

**Comment by nahuelon** [comment]
I'm going to split the issue in three tasks:
- [x] Add `--reporter` flag to the `test` command
- [ ] Add Github and JUnit reporters
- [ ] Add `cli.reporters` configuration
